Repository kcc-finalproject/KCC_STORE_INSPECTION_MANAGEMENT_SYSTEM, pull requests merged in 2024-10, with the labels that each got.

#2 [Setting] 배포 및 CI/CD 구축 테스트 #1
  backend/src/main/java/com/sims/admin/controller/AdminController.java
Labels: 🌏Deploy

#4 Feat/silder include
  backend/src/main/java/com/sims/main/controller/MainController.java
  backend/src/main/webapp/WEB-INF/views/index.jsp
  backend/src/main/webapp/WEB-INF/views/sidebar/sidebar.jsp
  backend/src/main/webapp/resources/css/sidebar/sidebar.css
  backend/src/main/webapp/resources/css/store_list/store_list.css
Labels: ✨Feature

#6 [#3] 가맹점 점검관리_가맹점 관리생성
  backend/.gitignore
  backend/src/main/java/com/sims/master/product_manage/controller/StoreController.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/controller/InspectionController.java
  backend/src/main/webapp/WEB-INF/views/index.jsp
  backend/src/main/webapp/WEB-INF/views/master/store_manage/store_list.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/inspection_schedule/schedule_list.jsp
  backend/src/main/webapp/WEB-INF/views/sidebar/sidebar.jsp
  backend/src/main/webapp/resources/css/master/store_manage/store_list.css
  backend/src/main/webapp/resources/css/qsc/inspection_schedule/schedule_list.css
  backend/src/main/webapp/resources/css/sidebar/sidebar.css
  backend/src/main/webapp/resources/css/store_list/store_list.css
  backend/src/main/webapp/resources/js/master/store_manage/store_list.js
  backend/src/main/webapp/resources/js/qsc/inspection_schedule/schedule_list.js
  backend/src/main/webapp/resources/js/sidebar/sidebar.js
Labels: ✨Feature

#8 체크리스트 관리 페이지 화면 구현 #7
  backend/src/main/java/com/sims/checklist/controller/ChecklistController.java
  backend/src/main/webapp/WEB-INF/views/checklist/list/checklist_list.jsp
  backend/src/main/webapp/WEB-INF/views/master/store_manage/store_list.jsp
  backend/src/main/webapp/resources/css/checklist/list/checklist_list.css
  backend/src/main/webapp/resources/js/checklist/list/checklist.js
Labels: ✨Feature

#10 점검페이지, 사이드바 페이지 구현 #9
  backend/src/main/java/com/sims/qsc/store_inspection/StoreInspectionController.java
  backend/src/main/resources/application.yml
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/popup_middleCheck.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/popup_page.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/popup_page_inspection.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/store_inspection.jsp
  backend/src/main/webapp/WEB-INF/views/sidebar/sidebar.jsp
  backend/src/main/webapp/resources/css/qsc/store_inspection/popup_inspection.css
  backend/src/main/webapp/resources/css/qsc/store_inspection/popup_middleCheck.css
  backend/src/main/webapp/resources/css/qsc/store_inspection/store_inspection.css
  backend/src/main/webapp/resources/css/qsc/store_inspection/store_inspection_popup.css
  backend/src/main/webapp/resources/css/sidebar/sidebar.css
  backend/src/main/webapp/resources/img/main_background.jpg
  backend/src/main/webapp/resources/js/qsc/store_inspection/maps.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/popup_inspection.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/popup_middleCheck.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/store_inspection.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/store_inspection_popup.js
  backend/src/main/webapp/resources/js/sidebar/sidebar.js
  backend/src/main/webapp/resources/map/seoul.json
Labels: ✨Feature

#11 [Feat] 가맹점관리 페이지 제작 #3
  .gitignore
  backend/src/main/resources/application.yml
  backend/src/main/webapp/WEB-INF/views/index.jsp
  backend/src/main/webapp/WEB-INF/views/master/store_manage/store_list.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/inspection_schedule/schedule_list.jsp
  backend/src/main/webapp/resources/css/master/store_manage/store_list.css
  backend/src/main/webapp/resources/css/qsc/inspection_schedule/schedule_list.css
  backend/src/main/webapp/resources/js/qsc/inspection_schedule/schedule_list.js
  backend/src/main/webapp/resources/js/sidebar/sidebar.js
Labels: ✨Feature

#13 [Feat]: 로그인 페이지 제작, 가맹점 점검 일정 조회 페이지 제작 #12
  backend/src/main/java/com/sims/main/controller/MainController.java
  backend/src/main/java/com/sims/qsc/store_inspection/StoreInspectionController.java
  backend/src/main/java/com/sims/qsc/store_inspection_schedule/StoreInspectionSchedule.java
  backend/src/main/webapp/WEB-INF/views/login.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection_schedule/store_inspection_schedule.jsp
  backend/src/main/webapp/resources/css/login.css
  backend/src/main/webapp/resources/css/qsc/store_inspection_schedule/store_inspection_schedule.css
  backend/src/main/webapp/resources/img/login_img.png
  backend/src/main/webapp/resources/js/login.js
  backend/src/main/webapp/resources/js/qsc/store_inspection_schedule/store_inspection_schedule.js
Labels: ✨Feature

#14 merge Develop to main
  .gitignore
  backend/.gitignore
  backend/pom.xml
  backend/src/main/java/com/sims/BackendApplication.java
  backend/src/main/java/com/sims/admin/controller/AdminController.java
  backend/src/main/java/com/sims/checklist/controller/ChecklistController.java
  backend/src/main/java/com/sims/main/controller/MainController.java
  backend/src/main/java/com/sims/master/product_manage/controller/StoreController.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/controller/InspectionController.java
  backend/src/main/java/com/sims/qsc/store_inspection/StoreInspectionController.java
  backend/src/main/java/com/sims/qsc/store_inspection_schedule/StoreInspectionSchedule.java
  backend/src/main/resources/application.yml
  backend/src/main/webapp/WEB-INF/views/checklist/list/checklist_list.jsp
  backend/src/main/webapp/WEB-INF/views/index.jsp
  backend/src/main/webapp/WEB-INF/views/login.jsp
  backend/src/main/webapp/WEB-INF/views/master/store_manage/store_list.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/inspection_schedule/schedule_list.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/popup_middleCheck.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/popup_page.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/popup_page_inspection.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/store_inspection.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection_schedule/store_inspection_schedule.jsp
  backend/src/main/webapp/WEB-INF/views/sidebar/sidebar.jsp
  backend/src/main/webapp/resources/css/checklist/list/checklist_list.css
  backend/src/main/webapp/resources/css/login.css
  backend/src/main/webapp/resources/css/master/store_manage/store_list.css
  backend/src/main/webapp/resources/css/qsc/inspection_schedule/schedule_list.css
  backend/src/main/webapp/resources/css/qsc/store_inspection/popup_inspection.css
  backend/src/main/webapp/resources/css/qsc/store_inspection/popup_middleCheck.css
  backend/src/main/webapp/resources/css/qsc/store_inspection/store_inspection.css
  backend/src/main/webapp/resources/css/qsc/store_inspection/store_inspection_popup.css
  backend/src/main/webapp/resources/css/qsc/store_inspection_schedule/store_inspection_schedule.css
  backend/src/main/webapp/resources/css/sidebar/sidebar.css
  backend/src/main/webapp/resources/img/login_img.png
  backend/src/main/webapp/resources/img/main_background.jpg
  backend/src/main/webapp/resources/js/checklist/list/checklist.js
  backend/src/main/webapp/resources/js/login.js
  backend/src/main/webapp/resources/js/master/store_manage/store_list.js
  backend/src/main/webapp/resources/js/qsc/inspection_schedule/schedule_list.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/maps.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/popup_inspection.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/popup_middleCheck.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/store_inspection.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/store_inspection_popup.js
  backend/src/main/webapp/resources/js/qsc/store_inspection_schedule/store_inspection_schedule.js
  backend/src/main/webapp/resources/js/sidebar/sidebar.js
  backend/src/main/webapp/resources/map/seoul.json
Labels: ⚙️Setting

#18 [Setting]: 폴더 구조 변경 #17
  backend/src/main/java/com/sims/admin/controller/AdminController.java
  backend/src/main/java/com/sims/home/dashboard/controller/MainController.java
  backend/src/main/java/com/sims/home/dashboard/domain/Member.java
  backend/src/main/java/com/sims/home/dashboard/mapper/DashboardMapper.java
  backend/src/main/java/com/sims/home/dashboard/service/DashboardService.java
  backend/src/main/java/com/sims/home/dashboard/service/DashboardServiceImpl.java
  backend/src/main/java/com/sims/home/dashboard/vo/LoginRequest.java
  backend/src/main/java/com/sims/master/checklist_manage/controller/controller/ChecklistController.java
  backend/src/main/java/com/sims/master/product_manage/controller/controller/StoreController.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/controller/controller/InspectionController.java
  backend/src/main/java/com/sims/qsc/store_inspection/controller/StoreInspectionController.java
  backend/src/main/java/com/sims/qsc/store_inspection_schedule/controller/StoreInspectionScheduleController.java
  backend/src/main/webapp/WEB-INF/views/master/checklist/list/checklist_list.jsp
  backend/src/main/webapp/resources/css/master/checklist/list/checklist_list.css
  backend/src/main/webapp/resources/js/master/checklist/list/checklist.js
Labels: ⚙️Setting

#20 [Feat]: 점검페이지 - 중간 점검 화면 구현 #9
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/popup_middleCheck.jsp
  backend/src/main/webapp/WEB-INF/views/sidebar/sidebar.jsp
  backend/src/main/webapp/resources/css/qsc/store_inspection/popup_middleCheck.css
  backend/src/main/webapp/resources/css/sidebar/sidebar.css
  backend/src/main/webapp/resources/js/qsc/store_inspection/popup_inspection.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/popup_middleCheck.js
Labels: ✨Feature

#21 [Feat]: 가맹점 점검모달 연결 체크리스트미리보기 연결 #16
  backend/src/main/webapp/WEB-INF/views/index.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/inspection_schedule/schedule_list.jsp
  backend/src/main/webapp/resources/css/qsc/inspection_schedule/schedule_list.css
  backend/src/main/webapp/resources/css/sidebar/sidebar.css
  backend/src/main/webapp/resources/js/qsc/inspection_schedule/schedule_list.js
  backend/src/main/webapp/resources/js/sidebar/sidebar.js
Labels: ✨Feature

#23 [Feature] 마스터 체크리스트 상세페이지 화면 구현
  backend/src/main/webapp/WEB-INF/views/master/checklist/list/checklist_list.jsp
  backend/src/main/webapp/resources/css/master/checklist/list/checklist_list.css
  backend/src/main/webapp/resources/css/sidebar/sidebar.css
  backend/src/main/webapp/resources/js/master/checklist/list/checklist.js
Labels: ✨Feature

#24 [Feat]: 가맹점 점검 조회 페이지 모달 생성 #22
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection_schedule/store_inspection_schedule.jsp
  backend/src/main/webapp/resources/css/qsc/store_inspection_schedule/store_inspection_schedule.css
  backend/src/main/webapp/resources/css/sidebar/sidebar.css
  backend/src/main/webapp/resources/js/qsc/store_inspection_schedule/store_inspection_schedule.js
Labels: ✨Feature

#28 [Feat] 가맹점 관리 페이지 제작 #27
  backend/src/main/java/com/sims/master/product_manage/controller/controller/StoreController.java
  backend/src/main/webapp/WEB-INF/views/master/store_manage/store_list.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/inspection_schedule/schedule_list.jsp
  backend/src/main/webapp/resources/css/master/store_manage/store_list.css
  backend/src/main/webapp/resources/css/qsc/inspection_schedule/schedule_list.css
  backend/src/main/webapp/resources/js/master/store_manage/maps.js
  backend/src/main/webapp/resources/js/master/store_manage/store_list.js
  backend/src/main/webapp/resources/js/qsc/inspection_schedule/schedule_list.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/maps.js
Labels: ✨Feature

#30 [Feature] 점검 항목 관리 페이지 화면 구현 #26
  backend/src/main/java/com/sims/master/inspection_list_manage/controller/Controller.java
  backend/src/main/webapp/WEB-INF/views/master/checklist/inspection_list_manage/inspection_list_manage.jsp
  backend/src/main/webapp/WEB-INF/views/sidebar/sidebar.jsp
  backend/src/main/webapp/resources/css/master/checklist/inspection_list_manage/inspection_list_manage.css
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/category.js
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/choice-list.js
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/evaluation.js
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/sub_category.js
  backend/src/main/webapp/resources/js/master/checklist/list/checklist.js
Labels: ✨Feature, 🎨Html&css

#34 [Feature] 빠른길찾기 기능 구현, 대시보드 #33
  backend/pom.xml
  backend/src/main/java/com/sims/qsc/inspection_schedule/controller/controller/InspectionController.java
  backend/src/main/java/com/sims/testMap/controller/MapController.java
  backend/src/main/java/com/sims/testMap/service/MapTestService.java
  backend/src/main/java/com/sims/testMap/vo/Coordinates.java
  backend/src/main/java/com/sims/testMap/vo/DrivingRequest.java
  backend/src/main/java/com/sims/testMap/vo/RouteRequest.java
  backend/src/main/java/com/sims/testMap/vo/RouteResponse.java
  backend/src/main/resources/application.yml
  backend/src/main/webapp/WEB-INF/views/index.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/inspection_result/result_list.jsp
  backend/src/main/webapp/WEB-INF/views/test.jsp
  backend/src/main/webapp/resources/css/qsc/inspection_result/result_list.css
  backend/src/main/webapp/resources/js/qsc/inspection_result/result.js
Labels: ✨Feature

#32 [Feat]: test 로그인 구현 #31
  backend/src/main/java/com/sims/config/PrincipalDetail.java
  backend/src/main/java/com/sims/config/PrincipalDetailService.java
  backend/src/main/java/com/sims/config/SecurityConfig.java
  backend/src/main/java/com/sims/home/dashboard/controller/HomeController.java
  backend/src/main/java/com/sims/home/dashboard/controller/MainController.java
  backend/src/main/java/com/sims/home/dashboard/domain/Member.java
  backend/src/main/java/com/sims/home/dashboard/mapper/MemberMapper.java
  backend/src/main/java/com/sims/home/dashboard/service/MemberService.java
  backend/src/main/java/com/sims/home/dashboard/service/MemberServiceImpl.java
  backend/src/main/java/com/sims/home/dashboard/vo/LoginRequest.java
  backend/src/main/java/com/sims/home/dashboard/vo/MemberDao.java
  backend/src/main/java/com/sims/home/dashboard/vo/MemberRegistRequest.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/mapper/home/memberMapper.xml
  backend/src/main/webapp/WEB-INF/views/home/login/login.jsp
  backend/src/main/webapp/resources/css/home/login/login.css
  backend/src/main/webapp/resources/js/home/login/login.js
Labels: ✨Feature

#35 [Feat]: 점검페이지 지도제외 화면 구현 #9
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/checkList_choice.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/popup_lastCheck.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/popup_middleCheck.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/popup_page_inspection.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/store_inspection.jsp
  backend/src/main/webapp/resources/css/qsc/store_inspection/checkList_choice.css
  backend/src/main/webapp/resources/css/qsc/store_inspection/popup_inspection.css
  backend/src/main/webapp/resources/css/qsc/store_inspection/popup_lastCheck.css
  backend/src/main/webapp/resources/css/qsc/store_inspection/popup_middleCheck.css
  backend/src/main/webapp/resources/css/qsc/store_inspection/store_inspection.css
  backend/src/main/webapp/resources/js/qsc/store_inspection/checkList_choice.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/maps.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/popup_inspection.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/popup_lastCheck.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/popup_middleCheck.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/store_inspection.js
Labels: ✨Feature

#37 [Feat]:마스터- 제품 관리 모달 및 페이지 생성 #29
  backend/src/main/java/com/sims/master/product_manage/controller/ProductController.java
  backend/src/main/java/com/sims/master/store_manage/controller/controller/StoreController.java
  backend/src/main/webapp/WEB-INF/views/master/product_manage/product_list.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection_schedule/store_inspection_schedule.jsp
  backend/src/main/webapp/resources/css/master/product_manage/product_list.css
  backend/src/main/webapp/resources/css/qsc/store_inspection_schedule/store_inspection_schedule.css
  backend/src/main/webapp/resources/js/master/product_manage/product_list.js
Labels: ✨Feature

#39 [Style] 점검 항목 관리 화면 수정 #38
  backend/src/main/webapp/WEB-INF/views/master/checklist/inspection_list_manage/inspection_list_manage.jsp
  backend/src/main/webapp/resources/css/master/checklist/inspection_list_manage/inspection_list_manage.css
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/category.js
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/choice-list.js
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/evaluation.js
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/sub_category.js
Labels: 🎨Html&css

#41 [Feat]: 사이드바 라우팅 수정 #40
  backend/src/main/java/com/sims/master/checklist_manage/controller/controller/ChecklistController.java
  backend/src/main/java/com/sims/master/inspection_list_manage/controller/InspectionListController.java
  backend/src/main/webapp/WEB-INF/views/sidebar/sidebar.jsp
Labels: ✨Feature

#44 [Feature] 빠른길찾기 기능 구현, 대시보드 #33
  backend/pom.xml
  backend/src/main/java/com/sims/home/dashboard/controller/HomeController.java
  backend/src/main/java/com/sims/testMap/controller/MapController.java
  backend/src/main/java/com/sims/testMap/controller/MapRestController.java
  backend/src/main/java/com/sims/testMap/service/MapTestService.java
  backend/src/main/java/com/sims/testMap/vo/Coordinates.java
  backend/src/main/java/com/sims/testMap/vo/RouteMatrix.java
  backend/src/main/java/com/sims/testMap/vo/RouteRequest.java
  backend/src/main/java/com/sims/testMap/vo/RouteResponse.java
  backend/src/main/java/com/sims/testMap/vo/TSPSolver.java
  backend/src/main/resources/application.yml
  backend/src/main/webapp/WEB-INF/views/qsc/inspection_schedule/schedule_list.jsp
  backend/src/main/webapp/WEB-INF/views/test.jsp
Labels: ✨Feature

#46 [Feat]: css 일괄수정#36
  backend/src/main/webapp/WEB-INF/views/master/checklist/inspection_list_manage/inspection_list_manage.jsp
  backend/src/main/webapp/WEB-INF/views/master/checklist/list/checklist_list.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/inspection_result/result_list.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/inspection_schedule/schedule_list.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection_schedule/store_inspection_schedule.jsp
  backend/src/main/webapp/WEB-INF/views/sidebar/sidebar.jsp
  backend/src/main/webapp/resources/css/master/checklist/inspection_list_manage/inspection_list_manage.css
  backend/src/main/webapp/resources/css/master/checklist/list/checklist_list.css
  backend/src/main/webapp/resources/css/qsc/inspection_result/result_list.css
  backend/src/main/webapp/resources/css/qsc/inspection_schedule/schedule_list.css
  backend/src/main/webapp/resources/css/qsc/store_inspection/store_inspection.css
  backend/src/main/webapp/resources/css/qsc/store_inspection_schedule/store_inspection_schedule.css
  backend/src/main/webapp/resources/css/sidebar/sidebar.css
Labels: 🎨Html&css

#48 [Feature] 지도 초안 & PDF 초안 #47
  backend/pom.xml
  backend/src/main/java/com/sims/testMap/service/MapTestService.java
  backend/src/main/java/com/sims/testMap/service/TemplatePDFParser.java
  backend/src/main/java/com/sims/testMap/vo/TSPSolver.java
  backend/src/main/webapp/WEB-INF/views/master/product_manage/product_list.jsp
  backend/src/main/webapp/WEB-INF/views/master/store_manage/store_list.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/inspection_schedule/schedule_list.jsp
  backend/src/main/webapp/WEB-INF/views/test.jsp
  backend/src/main/webapp/resources/css/master/product_manage/product_list.css
  backend/src/main/webapp/resources/css/master/store_manage/store_list.css
  backend/src/main/webapp/resources/css/qsc/inspection_schedule/schedule_list.css
  backend/src/main/webapp/resources/css/sidebar/sidebar.css
Labels: ✨Feature

#49 [Feat]: dashboard 화면 구현
  backend/src/main/java/com/sims/home/dashboard/controller/HomeController.java
  backend/src/main/webapp/WEB-INF/views/home/dashboard/dashboard.jsp
  backend/src/main/webapp/WEB-INF/views/master/checklist/inspection_list_manage/inspection_list_manage.jsp
  backend/src/main/webapp/resources/css/home/dashboard/dashboard.css
  backend/src/main/webapp/resources/js/home/dashboard/dashboard.js
Labels: ✨Feature, 🎨Html&css

#52 PDF 초안 #47
  backend/pom.xml
  backend/src/main/java/com/sims/testMap/controller/TestController.java
  backend/src/main/java/com/sims/testMap/service/TemplatePDFParser.java
  backend/src/main/java/com/sims/testMap/vo/DrivingRequest.java
  backend/src/main/webapp/WEB-INF/views/master/store_manage/store_list.jsp
  backend/src/main/webapp/WEB-INF/views/pdfTest.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/inspection_schedule/schedule_list.jsp
  backend/src/main/webapp/resources/css/master/store_manage/store_list.css
  backend/src/main/webapp/resources/js/home/dashboard/dashboard.js
  backend/src/main/webapp/resources/js/master/store_manage/store_list.js
  backend/src/main/webapp/resources/js/qsc/inspection_schedule/schedule_list.js
Labels: ✨Feature

#53 [Feat]: css일괄 수정 및 가맹점 점검페이지 수정 #50
  backend/src/main/webapp/WEB-INF/views/master/checklist/inspection_list_manage/inspection_list_manage.jsp
  backend/src/main/webapp/resources/css/master/checklist/inspection_list_manage/inspection_list_manage.css
  backend/src/main/webapp/resources/css/qsc/store_inspection/store_inspection.css
  backend/src/main/webapp/resources/css/qsc/store_inspection_schedule/store_inspection_schedule.css
  backend/src/main/webapp/resources/js/qsc/store_inspection/store_inspection.js
  backend/src/main/webapp/resources/js/qsc/store_inspection_schedule/store_inspection_schedule.js
Labels: ✨Feature, 🎨Html&css

#55 [Feature] 로그인 로그 저장 기능 구현
  backend/pom.xml
  backend/src/main/java/com/sims/BackendApplication.java
  backend/src/main/java/com/sims/aop/mapper/LogMapper.java
  backend/src/main/java/com/sims/aop/vo/LoginLogDao.java
  backend/src/main/java/com/sims/config/SecurityConfig.java
  backend/src/main/java/com/sims/config/common/ClientInfo.java
  backend/src/main/java/com/sims/config/common/EnvConfig.java
  backend/src/main/java/com/sims/config/security/CustomAuthenticationFailureHandler.java
  backend/src/main/java/com/sims/config/security/CustomAuthenticationSuccessHandler.java
  backend/src/main/java/com/sims/config/security/PrincipalDetail.java
  backend/src/main/java/com/sims/config/security/PrincipalDetailService.java
  backend/src/main/java/com/sims/config/security/SecurityConfig.java
  backend/src/main/java/com/sims/home/dashboard/controller/HomeController.java
  backend/src/main/java/com/sims/home/dashboard/mapper/MemberMapper.java
  backend/src/main/java/com/sims/home/dashboard/service/MemberService.java
  backend/src/main/java/com/sims/home/member/controller/MemberController.java
  backend/src/main/java/com/sims/home/member/mapper/MemberMapper.java
  backend/src/main/java/com/sims/home/member/service/MemberService.java
  backend/src/main/java/com/sims/home/member/service/MemberServiceImpl.java
  backend/src/main/java/com/sims/home/member/vo/MemberDao.java
  backend/src/main/java/com/sims/home/member/vo/MemberRegistRequest.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/mapper/home/memberMapper.xml
  backend/src/main/resources/mapper/log/logMapper.xml
Labels: ✨Feature

#56 [UI]: 전체화면 CSS 통합 수정 #50
  backend/src/main/webapp/WEB-INF/views/master/checklist/list/checklist_list.jsp
  backend/src/main/webapp/resources/css/master/checklist/inspection_list_manage/inspection_list_manage.css
  backend/src/main/webapp/resources/css/master/checklist/list/checklist_list.css
  backend/src/main/webapp/resources/css/qsc/inspection_schedule/schedule_list.css
  backend/src/main/webapp/resources/css/qsc/store_inspection/store_inspection.css
  backend/src/main/webapp/resources/js/master/checklist/list/checklist.js
  backend/src/main/webapp/resources/js/qsc/inspection_schedule/schedule_list.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/store_inspection.js
Labels: 🎨Html&css

#57 [UI] 리스트별 더보기 모달 버튼 통합 #54
  backend/src/main/java/com/sims/testMap/controller/TestController.java
  backend/src/main/webapp/WEB-INF/views/master/product_manage/product_list.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/inspection_schedule/schedule_list.jsp
  backend/src/main/webapp/resources/css/master/checklist/list/checklist_list.css
  backend/src/main/webapp/resources/css/master/product_manage/product_list.css
  backend/src/main/webapp/resources/css/master/store_manage/store_list.css
  backend/src/main/webapp/resources/css/qsc/inspection_result/result_list.css
  backend/src/main/webapp/resources/css/qsc/inspection_schedule/schedule_list.css
  backend/src/main/webapp/resources/js/master/checklist/list/checklist.js
  backend/src/main/webapp/resources/js/master/product_manage/product_list.js
  backend/src/main/webapp/resources/js/master/store_manage/store_list.js
  backend/src/main/webapp/resources/js/qsc/inspection_result/result.js
  backend/src/main/webapp/resources/js/qsc/inspection_schedule/schedule_list.js
Labels: 🎨Html&css

#61 [setting]: mapper convention define #60
  backend/src/main/java/com/sims/aop/TransactionAspect.java
  backend/src/main/java/com/sims/aop/vo/LoginLogDao.java
  backend/src/main/java/com/sims/aop/vo/TransactionLogDao.java
  backend/src/main/resources/mapper/home/memberMapper.xml
  backend/src/main/resources/mapper/log/logMapper.xml
Labels: ⚙️Setting

#62 [UI] 점검항목 관리 UI 수정 #59
  backend/src/main/webapp/WEB-INF/views/master/checklist/inspection_list_manage/inspection_list_manage.jsp
  backend/src/main/webapp/resources/css/master/checklist/inspection_list_manage/inspection_list_manage.css
  backend/src/main/webapp/resources/css/master/store_manage/store_list.css
  backend/src/main/webapp/resources/js/master/store_manage/store_list.js
Labels: 🎨Html&css

#63 [Style]: 체크리스트 관리 CSS 수정 #59
  backend/src/main/webapp/WEB-INF/views/master/checklist/inspection_list_manage/inspection_list_manage.jsp
  backend/src/main/webapp/WEB-INF/views/master/checklist/list/checklist_list.jsp
  backend/src/main/webapp/resources/css/master/checklist/inspection_list_manage/inspection_list_manage.css
  backend/src/main/webapp/resources/css/master/checklist/list/checklist_list.css
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/category.js
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/choice-list.js
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/evaluation.js
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/sub_category.js
  backend/src/main/webapp/resources/js/master/checklist/list/checklist.js
Labels: 🎨Html&css

#64 [Feat]: 가맹점 점검결과 페이지 화면 구현 및 검색바 드롭다운 구현 #59
  backend/src/main/webapp/WEB-INF/views/qsc/inspection_result/result_list.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/store_inspection.jsp
  backend/src/main/webapp/resources/css/qsc/inspection_result/result_list.css
  backend/src/main/webapp/resources/css/qsc/store_inspection/store_inspection.css
  backend/src/main/webapp/resources/js/qsc/inspection_result/result.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/store_inspection.js
Labels: ✨Feature, 🎨Html&css

#66 [Fix] 체크리스트, 점검 항목 페이지 CSS 수정
  backend/src/main/webapp/WEB-INF/views/master/checklist/inspection_list_manage/inspection_list_manage.jsp
  backend/src/main/webapp/WEB-INF/views/master/checklist/list/checklist_list.jsp
  backend/src/main/webapp/resources/css/master/checklist/inspection_list_manage/inspection_list_manage.css
  backend/src/main/webapp/resources/css/master/checklist/list/checklist_list.css
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/category.js
  backend/src/main/webapp/resources/js/master/checklist/list/checklist.js
Labels: 🎨Html&css

#68 [Style]: 가맹점 점검 완료 페이지및 체크리스트 관리페이지 CSS 수정 #67
  backend/src/main/webapp/resources/css/master/checklist/list/checklist_list.css
  backend/src/main/webapp/resources/css/qsc/inspection_result/result_list.css
  backend/src/main/webapp/resources/css/qsc/store_inspection/store_inspection.css
  backend/src/main/webapp/resources/js/qsc/store_inspection/popup_inspection.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/store_inspection.js
Labels: 🎨Html&css

#69 [Feat]: 점검페이지 스케줄 필터링 기능 추가 #58
  backend/src/main/java/com/sims/qsc/store_inspection/controller/StoreInspectionController.java
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/store_inspection.jsp
  backend/src/main/webapp/resources/js/qsc/store_inspection/store_inspection.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/store_inspection_popup.js
Labels: ✨Feature

#70 [Style]: 전체페이지 Css 일괄 수정 작업 #67
  backend/src/main/webapp/WEB-INF/views/master/checklist/list/checklist_list.jsp
  backend/src/main/webapp/WEB-INF/views/master/store_manage/store_list.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/inspection_schedule/schedule_list.jsp
  backend/src/main/webapp/resources/css/master/store_manage/store_list.css
  backend/src/main/webapp/resources/css/qsc/inspection_schedule/schedule_list.css
  backend/src/main/webapp/resources/js/master/store_manage/store_list.js
  backend/src/main/webapp/resources/js/qsc/inspection_schedule/schedule_list.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/popup_inspection.js
Labels: 🎨Html&css

#71 [HOTFIX]: 폴더구조 변경
  backend/src/main/java/com/sims/master/checklist_manage/controller/ChecklistController.java
  backend/src/main/java/com/sims/master/store_manage/controller/StoreController.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/controller/InspectionController.java
Labels: ⚙️Setting

#75 [Feat] 로그 저장 기능 구현
  backend/src/main/java/com/sims/aop/TransactionAspect.java
  backend/src/main/java/com/sims/aop/mapper/LogMapper.java
  backend/src/main/java/com/sims/aop/vo/TransactionLogDao.java
  backend/src/main/java/com/sims/config/security/CustomAuthenticationFailureHandler.java
  backend/src/main/java/com/sims/config/security/CustomAuthenticationSuccessHandler.java
  backend/src/main/java/com/sims/config/security/PrincipalDetailService.java
  backend/src/main/java/com/sims/config/security/SecurityConfig.java
  backend/src/main/java/com/sims/home/member/controller/MemberController.java
  backend/src/main/java/com/sims/home/member/mapper/MemberMapper.java
  backend/src/main/java/com/sims/home/member/service/MemberService.java
  backend/src/main/java/com/sims/home/member/service/MemberServiceImpl.java
  backend/src/main/java/com/sims/log/aop/TransactionErrorAspect.java
  backend/src/main/java/com/sims/log/aop/TransactionLogAspect.java
  backend/src/main/java/com/sims/log/mapper/LogMapper.java
  backend/src/main/java/com/sims/log/vo/LoginLogVo.java
  backend/src/main/java/com/sims/log/vo/TransactionErrorLogVo.java
  backend/src/main/java/com/sims/log/vo/TransactionLogVo.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/mapper/home/memberMapper.xml
  backend/src/main/resources/mapper/log/logMapper.xml
  backend/src/main/webapp/WEB-INF/views/home/login/login.jsp
Labels: ✨Feature

#77 [HOTFIX] 트랜잭션 로그 저장 기능 긴급 수정
  backend/src/main/java/com/sims/log/aop/TransactionErrorAspect.java
  backend/src/main/java/com/sims/log/aop/TransactionLogAspect.java
  backend/src/main/java/com/sims/log/vo/TransactionErrorLogVo.java
  backend/src/main/java/com/sims/log/vo/TransactionLogVo.java
  backend/src/main/java/com/sims/master/checklist_manage/controller/ChecklistController.java
  backend/src/main/java/com/sims/master/checklist_manage/mapper/ChecklistMapper.java
  backend/src/main/java/com/sims/master/checklist_manage/service/ChecklistService.java
  backend/src/main/java/com/sims/master/checklist_manage/service/ChecklistServiceImpl.java
  backend/src/main/java/com/sims/master/checklist_manage/vo/ChecklistVo.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/mapper/log/logMapper.xml
  backend/src/main/resources/mapper/master/checklist_manage/checklistMapper.xml
  backend/src/main/webapp/WEB-INF/views/master/checklist/list/checklist_list.jsp
  backend/src/main/webapp/WEB-INF/views/sidebar/sidebar.jsp
  backend/src/main/webapp/resources/css/master/checklist/list/checklist_list.css
  backend/src/main/webapp/resources/js/master/checklist/list/checklist.js
Labels: 🐞BugFix

#78 [Feat]: 가맹점 점검 일정 조회 API 구현 완성 #74
  backend/src/main/java/com/sims/qsc/store_inspection_schedule/controller/StoreInspectionScheduleController.java
  backend/src/main/java/com/sims/qsc/store_inspection_schedule/mapper/StoreInspectionScheduleMapper.java
  backend/src/main/java/com/sims/qsc/store_inspection_schedule/service/StoreInspectionScheduleService.java
  backend/src/main/java/com/sims/qsc/store_inspection_schedule/service/StoreInspectionScheduleServiceImpl.java
  backend/src/main/java/com/sims/qsc/store_inspection_schedule/vo/StoreInspectionSchedule.java
  backend/src/main/resources/mapper/qsc/storeInspectionScheduleMapper.xml
  backend/src/main/resources/mapper/qsc/store_inspection_schedule/storeInspectionScheduleMapper.xml
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection_schedule/store_inspection_schedule.jsp
  backend/src/main/webapp/resources/css/qsc/store_inspection_schedule/store_inspection_schedule.css
  backend/src/main/webapp/resources/js/qsc/store_inspection_schedule/store_inspection_schedule.js
Labels: ✨Feature

#80 [Fix]: 가맹점 점검 일정 조회 버그 undefined 수정 #79
  backend/src/main/resources/mapper/qsc/store_inspection_schedule/storeInspectionScheduleMapper.xml
  backend/src/main/webapp/resources/js/qsc/store_inspection_schedule/store_inspection_schedule.js
Labels: 🐞BugFix

#81 [Feat]: 가맹점 점검 계획관리 API 구현 #73
  backend/src/main/java/com/sims/qsc/inspection_schedule/controller/InspectionScheduleController.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/controller/InspectionScheduleRestController.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/mapper/InspectionScheduleMapper.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/service/InspectionScheduleService.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/service/InspectionScheduleServiceImpl.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/vo/InspectionDetailsBuilder.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/vo/InspectionScheduleBuilder.java
  backend/src/main/resources/mapper/qsc/inspection_schedule/InspectionScheduleMapper.xml
  backend/src/main/webapp/WEB-INF/views/home/login/login.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/inspection-schedule/schedule-list.jsp
  backend/src/main/webapp/WEB-INF/views/sidebar/sidebar.jsp
  backend/src/main/webapp/resources/js/qsc/inspection_schedule/schedule_list.js
Labels: ✨Feature

#83 [Setting]: 컨벤션 수정 #82
  backend/src/main/java/com/sims/config/security/PrincipalDetailService.java
  backend/src/main/java/com/sims/home/member/mapper/MemberMapper.java
  backend/src/main/java/com/sims/log/aop/TransactionErrorAspect.java
  backend/src/main/java/com/sims/log/aop/TransactionLogAspect.java
  backend/src/main/java/com/sims/master/checklist_manage/controller/ChecklistController.java
  backend/src/main/java/com/sims/master/checklist_manage/mapper/ChecklistMapper.java
  backend/src/main/java/com/sims/master/checklist_manage/service/ChecklistService.java
  backend/src/main/java/com/sims/master/checklist_manage/service/ChecklistServiceImpl.java
  backend/src/main/java/com/sims/master/checklist_manage/vo/ChecklistRequest.java
  backend/src/main/java/com/sims/master/checklist_manage/vo/ChecklistResponse.java
  backend/src/main/resources/mapper/home/memberMapper.xml
  backend/src/main/resources/mapper/log/logMapper.xml
  backend/src/main/resources/mapper/master/checklist_manage/checklistMapper.xml
  backend/src/main/webapp/WEB-INF/views/master/checklist/list/checklist_list.jsp
  backend/src/main/webapp/resources/js/master/checklist/list/checklist.js
Labels: 🔨Refactor, ⚙️Setting

#84 [Setting] 컨벤션 충돌 해결
  backend/src/main/java/com/sims/master/checklist_manage/controller/ChecklistController.java
  backend/src/main/java/com/sims/master/checklist_manage/mapper/ChecklistMapper.java
  backend/src/main/java/com/sims/master/checklist_manage/service/ChecklistService.java
  backend/src/main/java/com/sims/master/checklist_manage/service/ChecklistServiceImpl.java
  backend/src/main/webapp/resources/js/master/checklist/list/checklist.js
Labels: 🐞BugFix

#85 [Setting]: 컨벤션 충돌수정 #82
  backend/src/main/java/com/sims/qsc/store_inspection/controller/StoreInspectionController.java
  backend/src/main/java/com/sims/qsc/store_inspection/controller/StoreInspectionRestController.java
  backend/src/main/java/com/sims/qsc/store_inspection/mapper/StoreInspectionMapper.java
  backend/src/main/java/com/sims/qsc/store_inspection/mapper/StoreInspectionPopupMapper.java
  backend/src/main/java/com/sims/qsc/store_inspection/service/StoreInspectionPopup/StoreInspectionPopupService.java
  backend/src/main/java/com/sims/qsc/store_inspection/service/StoreInspectionPopup/StoreInspectionPopupServiceImpl.java
  backend/src/main/java/com/sims/qsc/store_inspection/service/StoreInspectionService.java
  backend/src/main/java/com/sims/qsc/store_inspection/service/StoreInspectionServiceImpl.java
  backend/src/main/java/com/sims/qsc/store_inspection/vo/RecentInspectionHistoryResponse.java
  backend/src/main/java/com/sims/qsc/store_inspection/vo/StoreInspectionPopupRequest.java
  backend/src/main/java/com/sims/qsc/store_inspection/vo/StoreInspectionResponse.java
  backend/src/main/resources/mapper/qsc/store_inspection/storeInspectionMapper.xml
  backend/src/main/resources/mapper/qsc/store_inspection/storeInspectionPopupMapper.xml
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/popup_page.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/popup_page_inspection.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/store_inspection.jsp
  backend/src/main/webapp/resources/css/qsc/store_inspection/popup_inspection.css
  backend/src/main/webapp/resources/js/qsc/store_inspection/popup_inspection.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/store_inspection.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/store_inspection_popup.js
Labels: ⚙️Setting

#86 [Setting]: 컨벤션 수정 #82
  backend/src/main/java/com/sims/qsc/inspection_schedule/controller/InspectionScheduleRestController.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/mapper/InspectionScheduleMapper.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/service/InspectionScheduleService.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/service/InspectionScheduleServiceImpl.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/vo/InspectionDetailsResponse.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/vo/InspectionScheduleBuilder.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/vo/InspectionScheduleRequest.java
  backend/src/main/resources/mapper/qsc/inspection_schedule/InspectionScheduleMapper.xml
  backend/src/main/webapp/WEB-INF/views/test.jsp
Labels: ⚙️Setting

#88 [Setting]: 컨벤션 수정 #82
  backend/src/main/java/com/sims/qsc/inspection_result/controller/InspectionResultController.java
  backend/src/main/java/com/sims/qsc/inspection_result/vo/InpectionResultVo.java
  backend/src/main/java/com/sims/qsc/store_inspection_schedule/controller/StoreInspectionScheduleController.java
  backend/src/main/java/com/sims/qsc/store_inspection_schedule/mapper/StoreInspectionScheduleMapper.java
  backend/src/main/java/com/sims/qsc/store_inspection_schedule/service/StoreInspectionScheduleService.java
  backend/src/main/java/com/sims/qsc/store_inspection_schedule/service/StoreInspectionScheduleServiceImpl.java
  backend/src/main/java/com/sims/qsc/store_inspection_schedule/vo/StoreInspectionSchedule.java
  backend/src/main/java/com/sims/qsc/store_inspection_schedule/vo/StoreInspectionScheduleRequest.java
  backend/src/main/java/com/sims/qsc/store_inspection_schedule/vo/StoreInspectionScheduleResponse.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/mapper/qsc/store_inspection_schedule/storeInspectionScheduleMapper.xml
  backend/src/main/webapp/WEB-INF/views/qsc/inspection_result/result_list.jsp
  backend/src/main/webapp/resources/js/qsc/inspection_result/result.js
Labels: 🐞BugFix

#89 [Feature] 권한 체크 AOP 구현
  backend/src/main/java/com/sims/Exception/CustomizedResponseEntityExceptionHandler.java
  backend/src/main/java/com/sims/Exception/ExceptionResponse.java
  backend/src/main/java/com/sims/config/Exception/CustomControllerAdvice.java
  backend/src/main/java/com/sims/config/Exception/CustomException.java
  backend/src/main/java/com/sims/config/Exception/ErrorCode.java
  backend/src/main/java/com/sims/config/Exception/ErrorResponseEntity.java
  backend/src/main/java/com/sims/config/common/aop/ARoleCheck.java
  backend/src/main/java/com/sims/config/common/aop/CRoleCheck.java
  backend/src/main/java/com/sims/config/common/aop/IRoleCheck.java
  backend/src/main/java/com/sims/config/common/aop/PRoleCheck.java
  backend/src/main/java/com/sims/config/common/aop/RoleCheckAspect.java
  backend/src/main/java/com/sims/config/common/aop/SRoleCheck.java
  backend/src/main/java/com/sims/config/security/PrincipalDetail.java
  backend/src/main/java/com/sims/config/security/PrincipalDetailService.java
  backend/src/main/java/com/sims/home/member/controller/MemberController.java
  backend/src/main/java/com/sims/home/member/mapper/MemberMapper.java
  backend/src/main/java/com/sims/home/member/service/MemberService.java
  backend/src/main/java/com/sims/home/member/service/MemberServiceImpl.java
  backend/src/main/java/com/sims/home/member/vo/Member.java
  backend/src/main/java/com/sims/home/member/vo/MemberDao.java
  backend/src/main/java/com/sims/home/member/vo/MemberRegistRequest.java
  backend/src/main/java/com/sims/log/aop/TransactionErrorAspect.java
  backend/src/main/java/com/sims/log/aop/TransactionLogAspect.java
  backend/src/main/java/com/sims/log/mapper/LogMapper.java
  backend/src/main/java/com/sims/log/vo/LoginLogVo.java
  backend/src/main/java/com/sims/log/vo/TransactionErrorLogVo.java
  backend/src/main/java/com/sims/log/vo/TransactionLogVo.java
  backend/src/main/java/com/sims/master/checklist_manage/controller/ChecklistController.java
  backend/src/main/java/com/sims/master/checklist_manage/mapper/ChecklistMapper.java
  backend/src/main/java/com/sims/master/checklist_manage/service/ChecklistService.java
  backend/src/main/java/com/sims/master/checklist_manage/service/ChecklistServiceImpl.java
  backend/src/main/java/com/sims/master/checklist_manage/vo/ChecklistDeleteRequest.java
  backend/src/main/java/com/sims/master/checklist_manage/vo/ChecklistOptionsResponse.java
  backend/src/main/java/com/sims/master/checklist_manage/vo/ChecklistRequest.java
  backend/src/main/java/com/sims/master/checklist_manage/vo/ChecklistResponse.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/mapper/home/memberMapper.xml
  backend/src/main/resources/mapper/log/logMapper.xml
  backend/src/main/resources/mapper/master/checklist_manage/checklistMapper.xml
  backend/src/main/webapp/WEB-INF/views/master/checklist/list/checklist_list.jsp
  backend/src/main/webapp/resources/css/master/checklist/list/checklist_list.css
  backend/src/main/webapp/resources/js/master/checklist/list/checklist.js
  backend/src/main/webapp/resources/js/master/checklist/list/checklist_modal.js
  backend/src/main/webapp/resources/js/qsc/store_inspection_schedule/store_inspection_schedule.js
Labels: ✨Feature

#92 [Fix]: 지도 마커안보이는 버그 수정 #90
  backend/src/main/java/com/sims/qsc/store_inspection/vo/StoreAllLocationResponse.java
  backend/src/main/resources/mapper/qsc/store_inspection/storeInspectionMapper.xml
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/store_inspection.jsp
  backend/src/main/webapp/resources/css/qsc/store_inspection/store_inspection.css
  backend/src/main/webapp/resources/js/qsc/store_inspection/maps.js
Labels: 🐞BugFix

#93 [Feature] 체크리스트 필터링 기능 추가
  backend/src/main/java/com/sims/config/Exception/ErrorCode.java
  backend/src/main/java/com/sims/master/checklist_manage/controller/ChecklistController.java
  backend/src/main/java/com/sims/master/checklist_manage/mapper/ChecklistMapper.java
  backend/src/main/java/com/sims/master/checklist_manage/service/ChecklistService.java
  backend/src/main/java/com/sims/master/checklist_manage/service/ChecklistServiceImpl.java
  backend/src/main/java/com/sims/master/checklist_manage/vo/ChecklistRequest.java
  backend/src/main/resources/mapper/master/checklist_manage/checklistMapper.xml
  backend/src/main/webapp/WEB-INF/views/master/checklist/list/checklist_list.jsp
  backend/src/main/webapp/resources/js/master/checklist/list/checklist.js
  backend/src/main/webapp/resources/js/master/checklist/list/checklist_filter.js
  backend/src/main/webapp/resources/js/master/checklist/list/checklist_modal.js
Labels: ✨Feature

#96 [Feat]: 가맹점 점검페이지 API 구현 #72
  backend/src/main/java/com/sims/qsc/store_inspection/controller/StoreInspectionController.java
  backend/src/main/java/com/sims/qsc/store_inspection/controller/StoreInspectionRestController.java
  backend/src/main/java/com/sims/qsc/store_inspection/mapper/StoreInspectionPopupMapper.java
  backend/src/main/java/com/sims/qsc/store_inspection/service/StoreInspectionPopup/StoreInspectionPopupService.java
  backend/src/main/java/com/sims/qsc/store_inspection/service/StoreInspectionPopup/StoreInspectionPopupServiceImpl.java
  backend/src/main/java/com/sims/qsc/store_inspection/service/StoreInspectionService.java
  backend/src/main/java/com/sims/qsc/store_inspection/vo/RecentInspectionHistoryResponse.java
  backend/src/main/java/com/sims/qsc/store_inspection/vo/StoreInspectionPopupRequest.java
  backend/src/main/java/com/sims/qsc/store_inspection/vo/StoreInspectionPopupResponse.java
  backend/src/main/resources/mapper/qsc/store_inspection/storeInspectionMapper.xml
  backend/src/main/resources/mapper/qsc/store_inspection/storeInspectionPopupMapper.xml
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/alert_error.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/popup_page.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/popup_page_inspection.jsp
  backend/src/main/webapp/resources/js/qsc/store_inspection/popup_inspection.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/store_inspection.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/store_inspection_popup.js
Labels: ✨Feature

#98 [Setting]: s3 연동 test #97
  backend/pom.xml
  backend/src/main/java/com/sims/config/s3/AwsFileController.java
  backend/src/main/java/com/sims/config/s3/AwsFileService.java
  backend/src/main/java/com/sims/config/s3/S3Config.java
  backend/src/main/java/com/sims/master/checklist_manage/controller/ChecklistController.java
  backend/src/main/java/com/sims/master/checklist_manage/mapper/ChecklistMapper.java
  backend/src/main/java/com/sims/master/checklist_manage/service/ChecklistService.java
  backend/src/main/java/com/sims/master/checklist_manage/service/ChecklistServiceImpl.java
  backend/src/main/java/com/sims/master/checklist_manage/vo/ChecklistDetailResponse.java
  backend/src/main/java/com/sims/master/inspection_list_manage/controller/InspectionListController.java
  backend/src/main/java/com/sims/master/inspection_list_manage/mapper/InspectionListManageMapper.java
  backend/src/main/java/com/sims/master/inspection_list_manage/service/InspectionListManageService.java
  backend/src/main/java/com/sims/master/inspection_list_manage/service/InspectionListManageServiceImpl.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/mapper/home/memberMapper.xml
  backend/src/main/resources/mapper/master/checklist_manage/inspectionListManageMapper.xml
  backend/src/main/webapp/WEB-INF/views/master/checklist/inspection_list_manage/inspection_list_manage.jsp
  backend/src/main/webapp/WEB-INF/views/master/checklist/list/checklist_list.jsp
  backend/src/main/webapp/WEB-INF/views/s3Test.jsp
  backend/src/main/webapp/WEB-INF/views/sidebar/sidebar.jsp
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/inspection_list_manage.js
  backend/src/main/webapp/resources/js/master/checklist/list/checklist.js
  backend/src/main/webapp/resources/js/master/checklist/list/checklist_filter.js
Labels: ⚙️Setting

#100 [Feat]:사이드, 탑바 구현, 가맹점 점검 임시저장 구현 #99
  backend/src/main/java/com/sims/login_user/controller/LoginUserRestController.java
  backend/src/main/java/com/sims/login_user/mapper/LoginUserMapper.java
  backend/src/main/java/com/sims/login_user/service/LoginUserService.java
  backend/src/main/java/com/sims/login_user/service/LoginUserServiceImpl.java
  backend/src/main/java/com/sims/login_user/vo/LoginUserResponse.java
  backend/src/main/java/com/sims/qsc/store_inspection/controller/StoreInspectionRestController.java
  backend/src/main/java/com/sims/qsc/store_inspection/mapper/StoreInspectionPopupMapper.java
  backend/src/main/java/com/sims/qsc/store_inspection/service/StoreInspectionPopup/StoreInspectionPopupService.java
  backend/src/main/java/com/sims/qsc/store_inspection/service/StoreInspectionPopup/StoreInspectionPopupServiceImpl.java
  backend/src/main/java/com/sims/qsc/store_inspection/vo/StoreInspectionPopupRequest.java
  backend/src/main/java/com/sims/qsc/store_inspection/vo/StoreInspectionPopupResponse.java
  backend/src/main/resources/mapper/loginUser/loginUserMapper.xml
  backend/src/main/resources/mapper/qsc/store_inspection/storeInspectionPopupMapper.xml
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/popup_page_inspection.jsp
  backend/src/main/webapp/WEB-INF/views/sidebar/sidebar.jsp
  backend/src/main/webapp/resources/css/sidebar/sidebar.css
  backend/src/main/webapp/resources/js/qsc/store_inspection/popup_inspection.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/store_inspection_popup.js
  backend/src/main/webapp/resources/js/sidebar/sidebar.js
Labels: ✨Feature, 🎨Html&css

#102 [Feat]: 가맹점 점검페이지 임시저장 구현 #72
  backend/src/main/java/com/sims/config/s3/AwsFileController.java
  backend/src/main/java/com/sims/qsc/store_inspection/mapper/StoreInspectionPopupMapper.java
  backend/src/main/java/com/sims/qsc/store_inspection/service/StoreInspectionPopup/StoreInspectionPopupServiceImpl.java
  backend/src/main/resources/mapper/qsc/store_inspection/storeInspectionPopupMapper.xml
  backend/src/main/webapp/resources/js/qsc/store_inspection/popup_inspection.js
Labels: ✨Feature

#104 [Feat}: 가맹점 점검결과 페이지 팝업 기능 구현 #87
  backend/src/main/java/com/sims/qsc/inspection_result/controller/InspectionResultController.java
  backend/src/main/java/com/sims/qsc/inspection_result/mapper/InspectionResultMapper.java
  backend/src/main/java/com/sims/qsc/inspection_result/mapper/InspectionResultPopupMapper.java
  backend/src/main/java/com/sims/qsc/inspection_result/service/InspectionResultService.java
  backend/src/main/java/com/sims/qsc/inspection_result/service/InspectionResultServiceImpl.java
  backend/src/main/java/com/sims/qsc/inspection_result/service/inspectionResultPopup/InspectionResultPopupService.java
  backend/src/main/java/com/sims/qsc/inspection_result/service/inspectionResultPopup/InspectionResultPopupServiceImpl.java
  backend/src/main/java/com/sims/qsc/inspection_result/vo/InspectionResultAnswImgResponse.java
  backend/src/main/java/com/sims/qsc/inspection_result/vo/InspectionResultCategoryDetailResponse.java
  backend/src/main/java/com/sims/qsc/inspection_result/vo/InspectionResultDetailResponse.java
  backend/src/main/java/com/sims/qsc/inspection_result/vo/InspectionResultRequest.java
  backend/src/main/java/com/sims/qsc/inspection_result/vo/InspectionResultResponse.java
  backend/src/main/java/com/sims/qsc/inspection_result/vo/InspectionResultSubCategoriesQuestionsResponse.java
  backend/src/main/java/com/sims/qsc/inspection_result/vo/InspectionResultSubCategoryDetailResponse.java
  backend/src/main/java/com/sims/qsc/store_inspection_schedule/controller/StoreInspectionScheduleController.java
  backend/src/main/resources/mapper/qsc/inspection_result/inspectionResultMapper.xml
  backend/src/main/resources/mapper/qsc/inspection_result/inspectionResultPopupMapper.xml
  backend/src/main/webapp/WEB-INF/views/qsc/inspection_result/popup_inspection_result.jsp
  backend/src/main/webapp/resources/css/qsc/inspection_result/popup_inspection_result.css
  backend/src/main/webapp/resources/js/qsc/inspection_result/popup_inspection_result.js
  backend/src/main/webapp/resources/js/qsc/inspection_result/result.js
  backend/test/com/sims/qsc/inspection_result/mapper/InspectionResultMapperTest.java
  backend/test/com/sims/qsc/inspection_result/mapper/InspectionResultPopupMapperTest.java
  backend/test/com/sims/qsc/inspection_result/service/inspectionResultPopup/InspectionResultPopupServiceImplTest.java
Labels: ✨Feature

#106 [Feat]: 가맹점 점검페이지 저장구현 #72
  backend/src/main/java/com/sims/qsc/store_inspection/mapper/StoreInspectionPopupMapper.java
  backend/src/main/java/com/sims/qsc/store_inspection/service/StoreInspectionPopup/StoreInspectionPopupServiceImpl.java
  backend/src/main/java/com/sims/qsc/store_inspection/vo/StoreInspectionPopupResponse.java
  backend/src/main/resources/mapper/qsc/store_inspection/storeInspectionPopupMapper.xml
  backend/src/main/webapp/resources/js/qsc/store_inspection/popup_inspection.js
Labels: ✨Feature

#109 [Feat]: 가맹점 점검 목록 API 구현 및 UI 변경 #108
  backend/pom.xml
  backend/src/main/java/com/sims/master/product_manage/controller/ProductController.java
  backend/src/main/java/com/sims/master/product_manage/mapper/ProductMapper.java
  backend/src/main/java/com/sims/master/product_manage/service/ProductService.java
  backend/src/main/java/com/sims/master/product_manage/service/ProductServiceImpl.java
  backend/src/main/java/com/sims/master/product_manage/vo/ProductOptionsResponse.java
  backend/src/main/java/com/sims/master/product_manage/vo/ProductRequest.java
  backend/src/main/java/com/sims/master/product_manage/vo/ProductResponse.java
  backend/src/main/java/com/sims/qsc/store_inspection_schedule/controller/StoreInspectionScheduleController.java
  backend/src/main/resources/mapper/master/product_manage/productMapper.xml
  backend/src/main/resources/mapper/qsc/store_inspection_schedule/storeInspectionScheduleMapper.xml
  backend/src/main/webapp/WEB-INF/views/master/product_manage/product_list.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/inspection_result/result_list.jsp
  backend/src/main/webapp/resources/css/master/product_manage/product_list.css
  backend/src/main/webapp/resources/js/master/product_manage/product_filter.js
  backend/src/main/webapp/resources/js/master/product_manage/product_list.js
  backend/src/main/webapp/resources/js/qsc/inspection_result/popup_inspection_result.js
  backend/src/main/webapp/resources/js/qsc/inspection_result/result.js
  backend/src/main/webapp/resources/js/qsc/inspection_result/result_filter.js
  backend/test/com/sims/master/product_manage/mapper/ProductMapperTest.java
Labels: ✨Feature, 🎨Html&css

#110 [Feat]: 가맹점 점검페이지 API 임시저장 구현 완료 #72
  backend/src/main/java/com/sims/qsc/store_inspection/controller/StoreInspectionController.java
  backend/src/main/java/com/sims/qsc/store_inspection/mapper/StoreInspectionPopupMapper.java
  backend/src/main/java/com/sims/qsc/store_inspection/service/StoreInspectionPopup/StoreInspectionPopupService.java
  backend/src/main/java/com/sims/qsc/store_inspection/service/StoreInspectionPopup/StoreInspectionPopupServiceImpl.java
  backend/src/main/java/com/sims/qsc/store_inspection/vo/StoreInspectionPopupRequest.java
  backend/src/main/java/com/sims/qsc/store_inspection/vo/StoreInspectionPopupResponse.java
  backend/src/main/resources/mapper/qsc/store_inspection/storeInspectionPopupMapper.xml
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/popup_page_inspection.jsp
  backend/src/main/webapp/resources/js/qsc/store_inspection/popup_inspection.js
Labels: ✨Feature

#111 [Feat]: 가맹점 점검 연결 #73
  backend/pom.xml
  backend/src/main/java/com/sims/master/product_manage/controller/ProductController.java
  backend/src/main/java/com/sims/master/product_manage/mapper/ProductMapper.java
  backend/src/main/java/com/sims/master/product_manage/service/ProductServiceImpl.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/controller/InspectionScheduleController.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/controller/InspectionScheduleRestController.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/mapper/InspectionScheduleMapper.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/service/InspectionScheduleService.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/service/InspectionScheduleServiceImpl.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/vo/InspectionScheduleRequest.java
  backend/src/main/resources/mapper/qsc/inspection_schedule/InspectionScheduleMapper.xml
  backend/src/main/resources/mapper/qsc/store_inspection_schedule/storeInspectionScheduleMapper.xml
  backend/src/main/webapp/WEB-INF/views/qsc/inspection-schedule/schedule-list.jsp
  backend/src/main/webapp/resources/css/qsc/inspection_schedule/schedule_list.css
  backend/src/main/webapp/resources/js/qsc/inspection_schedule/schedule_list.js
Labels: ✨Feature
