Repository kcc-finalproject/KCC_STORE_INSPECTION_MANAGEMENT_SYSTEM, pull requests merged in 2024-11, with the labels that each got.

#112 [Feature] 점검 항목 관리 페이지 대분류, 중분류 기능 구현 #103
  backend/src/main/java/com/sims/master/checklist_manage/mapper/ChecklistMapper.java
  backend/src/main/java/com/sims/master/checklist_manage/service/ChecklistService.java
  backend/src/main/java/com/sims/master/checklist_manage/service/ChecklistServiceImpl.java
  backend/src/main/java/com/sims/master/inspection_list_manage/controller/InspectionListController.java
  backend/src/main/java/com/sims/master/inspection_list_manage/mapper/InspectionListManageMapper.java
  backend/src/main/java/com/sims/master/inspection_list_manage/service/InspectionListManageService.java
  backend/src/main/java/com/sims/master/inspection_list_manage/service/InspectionListManageServiceImpl.java
  backend/src/main/java/com/sims/master/inspection_list_manage/vo/ChclstResponse.java
  backend/src/main/java/com/sims/master/inspection_list_manage/vo/CtgRequest.java
  backend/src/main/java/com/sims/master/inspection_list_manage/vo/CtgResponse.java
  backend/src/main/java/com/sims/master/inspection_list_manage/vo/EvitResponse.java
  backend/src/main/java/com/sims/master/inspection_list_manage/vo/SubCtgRequest.java
  backend/src/main/java/com/sims/master/inspection_list_manage/vo/SubCtgResponse.java
  backend/src/main/resources/mapper/master/checklist_manage/checklistMapper.xml
  backend/src/main/resources/mapper/master/checklist_manage/inspectionListManageMapper.xml
  backend/src/main/webapp/WEB-INF/views/master/checklist/inspection_list_manage/inspection_list_manage.jsp
  backend/src/main/webapp/resources/css/master/checklist/inspection_list_manage/inspection_list_manage.css
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/category.js
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/choice-list.js
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/evaluation.js
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/master-modal.js
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/sub_category.js
  backend/src/main/webapp/resources/js/master/checklist/list/checklist.js
Labels: ✨Feature, 🎨Html&css

#113 [Feat]: 가맹점 관리 및 제품 관리 페이지 API 기능 구현 #108
  backend/src/main/java/com/sims/config/Exception/ErrorCode.java
  backend/src/main/java/com/sims/config/s3/AwsFileController.java
  backend/src/main/java/com/sims/config/s3/AwsFileService.java
  backend/src/main/java/com/sims/master/product_manage/controller/ProductController.java
  backend/src/main/java/com/sims/master/product_manage/mapper/ProductMapper.java
  backend/src/main/java/com/sims/master/product_manage/service/ProductService.java
  backend/src/main/java/com/sims/master/product_manage/service/ProductServiceImpl.java
  backend/src/main/java/com/sims/master/product_manage/vo/ProductDeleteRequest.java
  backend/src/main/java/com/sims/master/product_manage/vo/ProductRequest.java
  backend/src/main/java/com/sims/master/store_manage/controller/StoreController.java
  backend/src/main/java/com/sims/master/store_manage/mapper/StoreMapper.java
  backend/src/main/java/com/sims/master/store_manage/service/StoreService.java
  backend/src/main/java/com/sims/master/store_manage/service/StoreServiceImpl.java
  backend/src/main/java/com/sims/master/store_manage/vo/InspectorInfoRequest.java
  backend/src/main/java/com/sims/master/store_manage/vo/InspectorNmsResponse.java
  backend/src/main/java/com/sims/master/store_manage/vo/StoreDeleteRequest.java
  backend/src/main/java/com/sims/master/store_manage/vo/StoreModalResponse.java
  backend/src/main/java/com/sims/master/store_manage/vo/StoreOptionsResponse.java
  backend/src/main/java/com/sims/master/store_manage/vo/StoreRequest.java
  backend/src/main/java/com/sims/master/store_manage/vo/StoreResponse.java
  backend/src/main/java/com/sims/master/store_manage/vo/SvNmsResponse.java
  backend/src/main/java/com/sims/qsc/inspection_result/controller/InspectionResultController.java
  backend/src/main/java/com/sims/qsc/inspection_result/mapper/InspectionResultMapper.java
  backend/src/main/java/com/sims/qsc/inspection_result/service/InspectionResultService.java
  backend/src/main/resources/mapper/master/product_manage/productMapper.xml
  backend/src/main/resources/mapper/master/store_manage/storeMapper.xml
  backend/src/main/webapp/WEB-INF/views/master/product_manage/product_list.jsp
  backend/src/main/webapp/WEB-INF/views/master/store_manage/store_list.jsp
  backend/src/main/webapp/WEB-INF/views/sidebar/sidebar.jsp
  backend/src/main/webapp/resources/css/master/product_manage/product_list.css
  backend/src/main/webapp/resources/css/master/store_manage/store_list.css
  backend/src/main/webapp/resources/js/master/product_manage/product_filter.js
  backend/src/main/webapp/resources/js/master/product_manage/product_list.js
  backend/src/main/webapp/resources/js/master/product_manage/product_modal.js
  backend/src/main/webapp/resources/js/master/store_manage/maps.js
  backend/src/main/webapp/resources/js/master/store_manage/store_filter.js
  backend/src/main/webapp/resources/js/master/store_manage/store_list.js
  backend/src/main/webapp/resources/js/master/store_manage/store_modal.js
  backend/src/main/webapp/resources/js/qsc/inspection_result/result.js
  backend/src/main/webapp/resources/js/qsc/store_inspection_schedule/store_inspection_schedule.js
  backend/test/com/sims/master/product_manage/mapper/ProductMapperTest.java
  backend/test/com/sims/master/product_manage/service/ProductServiceImplTest.java
  backend/test/com/sims/master/store_manage/mapper/StoreMapperTest.java
Labels: ✨Feature, 🎨Html&css

#114 [Feature]: 점검 항목 관리 API 구현
  backend/src/main/java/com/sims/master/inspection_list_manage/controller/InspectionListController.java
  backend/src/main/java/com/sims/master/inspection_list_manage/mapper/InspectionListManageMapper.java
  backend/src/main/java/com/sims/master/inspection_list_manage/service/InspectionListManageService.java
  backend/src/main/java/com/sims/master/inspection_list_manage/service/InspectionListManageServiceImpl.java
  backend/src/main/java/com/sims/master/inspection_list_manage/vo/ChclstRequest.java
  backend/src/main/java/com/sims/master/inspection_list_manage/vo/EvitRequest.java
  backend/src/main/resources/mapper/master/checklist_manage/inspectionListManageMapper.xml
  backend/src/main/webapp/WEB-INF/views/master/checklist/inspection_list_manage/inspection_list_manage.jsp
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/category.js
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/choice-list.js
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/evaluation.js
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/modal.js
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/sub_category.js
Labels: ✨Feature

#116 [Feature] 가맹점 점검 로직 구현 #115
  backend/src/main/java/com/sims/qsc/inspection_schedule/controller/InspectionScheduleController.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/controller/InspectionScheduleRestController.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/mapper/InspectionScheduleMapper.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/service/InspectionScheduleService.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/service/InspectionScheduleServiceImpl.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/service/InspectionScheduleServiceImpl_back.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/vo/InspectionPlan.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/vo/InspectionSchedule.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/vo/InspectionScheduleRequest.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/vo/MemberRequest.java
  backend/src/main/resources/mapper/qsc/inspection_schedule/InspectionScheduleMapper.xml
  backend/src/main/webapp/WEB-INF/views/qsc/inspection-schedule/schedule-list.jsp
  backend/src/main/webapp/resources/js/qsc/inspection_schedule/schedule_list.js
  backend/src/main/webapp/resources/js/qsc/inspection_schedule/schedule_list_back.js
Labels: ✨Feature

#117 [Feat]:가맹점 점검페이지 API 구현 #72
  backend/src/main/java/com/sims/config/s3/AwsFileController.java
  backend/src/main/java/com/sims/config/s3/AwsFileService.java
  backend/src/main/java/com/sims/qsc/store_inspection/controller/StoreInspectionController.java
  backend/src/main/java/com/sims/qsc/store_inspection/controller/StoreInspectionRestController.java
  backend/src/main/java/com/sims/qsc/store_inspection/mapper/StoreInspectionPopupMapper.java
  backend/src/main/java/com/sims/qsc/store_inspection/service/StoreInspectionPopup/StoreInspectionPopupService.java
  backend/src/main/java/com/sims/qsc/store_inspection/service/StoreInspectionPopup/StoreInspectionPopupServiceImpl.java
  backend/src/main/java/com/sims/qsc/store_inspection/vo/RecentInspectionHistoryResponse.java
  backend/src/main/java/com/sims/qsc/store_inspection/vo/StoreInspectionPopupRequest.java
  backend/src/main/java/com/sims/qsc/store_inspection/vo/StoreInspectionPopupResponse.java
  backend/src/main/java/com/sims/qsc/store_inspection/vo/StoreInspectionResponse.java
  backend/src/main/resources/mapper/qsc/store_inspection/storeInspectionMapper.xml
  backend/src/main/resources/mapper/qsc/store_inspection/storeInspectionPopupMapper.xml
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/popup_middleCheck.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/popup_signature.jsp
  backend/src/main/webapp/resources/css/qsc/store_inspection/popup_inspection.css
  backend/src/main/webapp/resources/css/qsc/store_inspection/store_inspection.css
  backend/src/main/webapp/resources/js/qsc/store_inspection/popup_inspection.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/popup_middleCheck.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/popup_signature.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/store_inspection.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/store_inspection_popup.js
Labels: ✨Feature

#118 [Fix]: 새로고침 수정 #103
  backend/src/main/java/com/sims/master/inspection_list_manage/service/InspectionListManageServiceImpl.java
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/category.js
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/choice-list.js
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/evaluation.js
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/sub_category.js
Labels: ✨Feature

#119 [Feat]: 가맹점 점검페이지 API 기능구현 완료 #72
  backend/src/main/webapp/resources/js/qsc/store_inspection/popup_middleCheck.js
Labels: ✨Feature

#123 [Feat]: 대시보드, 점검페이지 ui, 기능 수정 #122
  backend/src/main/webapp/resources/css/qsc/store_inspection/alert_error.css
  backend/src/main/webapp/resources/css/qsc/store_inspection/store_inspection.css
  backend/src/main/webapp/resources/js/qsc/store_inspection/alert_error.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/store_inspection.js
Labels: ✨Feature, 🎨Html&css

#125 [Feat]: 가맹점 점검페이지 API 구현 및 수정 #72
  backend/src/main/webapp/resources/js/qsc/store_inspection/alert_error.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/popup_middleCheck.js
Labels: 🐞BugFix, ✨Feature

#127 [Fix]: 가맹점 관리, 제품 관리 페이지 오류 수정 #126
  backend/src/main/java/com/sims/master/store_manage/controller/StoreController.java
  backend/src/main/java/com/sims/master/store_manage/mapper/StoreMapper.java
  backend/src/main/java/com/sims/master/store_manage/service/StoreService.java
  backend/src/main/java/com/sims/master/store_manage/service/StoreServiceImpl.java
  backend/src/main/java/com/sims/master/store_manage/vo/StoreOptionsResponse.java
  backend/src/main/java/com/sims/qsc/inspection_result/controller/InspectionResultController.java
  backend/src/main/resources/mapper/master/product_manage/productMapper.xml
  backend/src/main/resources/mapper/master/store_manage/storeMapper.xml
  backend/src/main/webapp/WEB-INF/views/master/product_manage/product_list.jsp
  backend/src/main/webapp/WEB-INF/views/master/store_manage/store_list.jsp
  backend/src/main/webapp/resources/css/common/common.css
  backend/src/main/webapp/resources/css/master/product_manage/product_list.css
  backend/src/main/webapp/resources/css/master/store_manage/store_list.css
  backend/src/main/webapp/resources/js/master/product_manage/product_filter.js
  backend/src/main/webapp/resources/js/master/product_manage/product_list.js
  backend/src/main/webapp/resources/js/master/product_manage/product_modal.js
  backend/src/main/webapp/resources/js/master/store_manage/store_filter.js
  backend/src/main/webapp/resources/js/master/store_manage/store_list.js
  backend/src/main/webapp/resources/js/master/store_manage/store_modal.js
  backend/src/main/webapp/resources/js/qsc/inspection_result/popup_inspection_result.js
Labels: 🐞BugFix

#128 [Feat]: 가맹점 점검 삽입 구현 #115
  backend/src/main/java/com/sims/qsc/inspection_schedule/mapper/InspectionScheduleMapper.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/service/InspectionScheduleService.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/service/InspectionScheduleServiceImpl.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/service/InspectionScheduleServiceImpl_back.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/vo/InspectionPlan.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/vo/InspectionSchedule.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/vo/InspectionScheduleRequest.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/vo/MemberRequest.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/mapper/qsc/inspection_schedule/InspectionScheduleMapper.xml
  backend/src/main/resources/mapper/qsc/store_inspection/storeInspectionMapper.xml
  backend/src/main/webapp/resources/js/qsc/inspection_schedule/schedule_list.js
  backend/src/main/webapp/resources/js/qsc/inspection_schedule/schedule_list_back.js
Labels: ✨Feature

#129 [Feature] 대시보드 API 연결 및 UI 수정
  backend/src/main/java/com/sims/home/dashboard/controller/DashboardController.java
  backend/src/main/java/com/sims/home/dashboard/controller/HomeController.java
  backend/src/main/java/com/sims/home/dashboard/mapper/DashboardMapper.java
  backend/src/main/java/com/sims/home/dashboard/service/DashboardService.java
  backend/src/main/java/com/sims/home/dashboard/service/DashboardServiceImpl.java
  backend/src/main/java/com/sims/home/dashboard/vo/BsnSspnResponse.java
  backend/src/main/java/com/sims/home/dashboard/vo/InspSchdAndResultResponse.java
  backend/src/main/java/com/sims/home/dashboard/vo/NotCompleteResponse.java
  backend/src/main/java/com/sims/home/dashboard/vo/PenaltyResponse.java
  backend/src/main/java/com/sims/home/dashboard/vo/RecentInspResultResponse.java
  backend/src/main/java/com/sims/master/checklist_manage/controller/ChecklistController.java
  backend/src/main/java/com/sims/qsc/store_inspection/controller/StoreInspectionController.java
  backend/src/main/resources/mapper/home/dashboardMapper.xml
  backend/src/main/webapp/WEB-INF/views/home/dashboard/dashboard.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/alert_error.jsp
  backend/src/main/webapp/resources/css/home/dashboard/dashboard.css
  backend/src/main/webapp/resources/css/qsc/store_inspection/alert_error.css
  backend/src/main/webapp/resources/js/home/dashboard/dashboard.js
  backend/src/main/webapp/resources/js/master/checklist/list/checklist.js
  backend/src/main/webapp/resources/js/master/checklist/list/checklist_filter.js
Labels: ✨Feature

#130 [HOTFIX]: 페이징 수정
  backend/src/main/resources/mapper/home/dashboardMapper.xml
Labels: ✨Feature

#131 [HOTFIX]: 가맹점 점검결과 버그 수정
  backend/src/main/resources/mapper/master/product_manage/productMapper.xml
  backend/src/main/webapp/resources/js/master/product_manage/product_filter.js
  backend/src/main/webapp/resources/js/master/product_manage/product_list.js
  backend/src/main/webapp/resources/js/qsc/inspection_result/popup_inspection_result.js
Labels: 🐞BugFix

#133 [Fix]: 로그인 페이지 기능 수정
  backend/src/main/java/com/sims/config/security/SecurityConfig.java
  backend/src/main/java/com/sims/home/member/vo/Member.java
  backend/src/main/java/com/sims/log/vo/LoginLogVo.java
  backend/src/main/webapp/WEB-INF/views/home/login/login.jsp
  backend/src/main/webapp/resources/js/home/login/login.js
Labels: 🐞BugFix

#136 [Refactor]: 점검결과 페이지 그리드 기능 수정 및 검색 기능 수정 #135
  backend/src/main/java/com/sims/config/Exception/ErrorCode.java
  backend/src/main/java/com/sims/qsc/inspection_result/controller/InspectionResultController.java
  backend/src/main/java/com/sims/qsc/inspection_result/mapper/InspectionResultMapper.java
  backend/src/main/java/com/sims/qsc/inspection_result/service/InspectionResultService.java
  backend/src/main/java/com/sims/qsc/inspection_result/service/InspectionResultServiceImpl.java
  backend/src/main/java/com/sims/qsc/inspection_result/vo/InspectionResultOptionResponse.java
  backend/src/main/java/com/sims/qsc/inspection_result/vo/InspectionResultRequest.java
  backend/src/main/java/com/sims/qsc/inspection_result/vo/InspectionResultResponse.java
  backend/src/main/java/com/sims/qsc/inspection_result/vo/InspectorNmsResponse.java
  backend/src/main/resources/mapper/qsc/inspection_result/inspectionResultMapper.xml
  backend/src/main/webapp/WEB-INF/views/master/product_manage/product_list.jsp
  backend/src/main/webapp/WEB-INF/views/master/store_manage/store_list.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/inspection_result/result_list.jsp
  backend/src/main/webapp/resources/css/qsc/inspection_result/result_list.css
  backend/src/main/webapp/resources/js/master/product_manage/product_filter.js
  backend/src/main/webapp/resources/js/master/product_manage/product_list.js
  backend/src/main/webapp/resources/js/master/store_manage/store_filter.js
  backend/src/main/webapp/resources/js/qsc/inspection_result/result.js
  backend/src/main/webapp/resources/js/qsc/inspection_result/result_filter.js
  backend/test/com/sims/qsc/inspection_result/mapper/InspectionResultMapperTest.java
Labels: 🎨Html&css, 🔨Refactor

#137 [Fix] 테스트 수정
  backend/src/main/java/com/sims/master/checklist_manage/mapper/ChecklistMapper.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/mapper/master/checklist_manage/checklistMapper.xml
  backend/src/main/webapp/WEB-INF/views/master/checklist/list/checklist_list.jsp
  backend/src/main/webapp/resources/css/master/checklist/list/checklist_list.css
Labels: 🐞BugFix

#138 [Feat]: 가맹점 점검 삽입 구현 ##115
  backend/src/main/java/com/sims/qsc/inspection_schedule/service/InspectionScheduleServiceImpl.java
  backend/src/main/resources/mapper/qsc/inspection_schedule/InspectionScheduleMapper.xml
  backend/src/main/webapp/resources/js/qsc/inspection_schedule/schedule_list.js
  backend/src/main/webapp/resources/js/qsc/inspection_schedule/schedule_list_back.js
Labels: ✨Feature

#139 [Feat]: 가맹점 점검페이지 API 구현 수정 및 대시보드 수정 #72
  backend/src/main/java/com/sims/qsc/store_inspection/vo/StoreInspectionResponse.java
  backend/src/main/resources/mapper/qsc/store_inspection/storeInspectionMapper.xml
  backend/src/main/webapp/WEB-INF/views/home/dashboard/dashboard.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/store-inspection.jsp
  backend/src/main/webapp/resources/css/qsc/store_inspection/alert_error.css
  backend/src/main/webapp/resources/js/qsc/store_inspection/alert_error.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/popup_middleCheck.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/store_inspection.js
Labels: 🐞BugFix, ✨Feature, 🎨Html&css

#140 [Feat]: 가맹점 점검페이지 점검유형 필터링 수정, css 추가 #72
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/popup-page-inspection.jsp
  backend/src/main/webapp/resources/css/qsc/store_inspection/popup_inspection.css
  backend/src/main/webapp/resources/css/qsc/store_inspection/popup_middleCheck.css
  backend/src/main/webapp/resources/css/qsc/store_inspection/popup_signature.css
  backend/src/main/webapp/resources/css/qsc/store_inspection/store_inspection.css
  backend/src/main/webapp/resources/js/qsc/store_inspection/store_inspection.js
Labels: ✨Feature, 🎨Html&css

#142 [Feat]: 가맹점 점검 삽입 구현 #115
  backend/src/main/java/com/sims/qsc/inspection_schedule/mapper/InspectionScheduleMapper.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/service/InspectionScheduleService.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/service/InspectionScheduleServiceImpl.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/service/InspectionScheduleServiceImpl_back.java
  backend/src/main/resources/mapper/qsc/inspection_schedule/InspectionScheduleMapper.xml
Labels: ✨Feature

#143 [Refactor]: 마스터관리 페이지 반응형 디자인 수정 및 점검결과 API 응답속도 개선 #141
  backend/src/main/java/com/sims/master/product_manage/service/ProductServiceImpl.java
  backend/src/main/java/com/sims/master/store_manage/controller/StoreController.java
  backend/src/main/java/com/sims/master/store_manage/service/StoreServiceImpl.java
  backend/src/main/java/com/sims/qsc/inspection_result/mapper/InspectionResultPopupMapper.java
  backend/src/main/java/com/sims/qsc/inspection_result/service/inspectionResultPopup/InspectionResultPopupServiceImpl.java
  backend/src/main/java/com/sims/qsc/inspection_result/vo/InspectionResultCategoryDetailResponse.java
  backend/src/main/java/com/sims/qsc/inspection_result/vo/InspectionResultSubCategoryDetailResponse.java
  backend/src/main/resources/mapper/qsc/inspection_result/inspectionResultPopupMapper.xml
  backend/src/main/webapp/WEB-INF/views/qsc/inspection_result/result_list.jsp
  backend/src/main/webapp/resources/css/master/product_manage/product_list.css
  backend/src/main/webapp/resources/css/master/store_manage/store_list.css
  backend/src/main/webapp/resources/css/qsc/inspection_result/popup_inspection_result.css
  backend/src/main/webapp/resources/js/master/store_manage/maps.js
  backend/src/main/webapp/resources/js/master/store_manage/store_list.js
  backend/src/main/webapp/resources/js/master/store_manage/store_modal.js
  backend/src/main/webapp/resources/js/qsc/inspection_result/popup_inspection_result.js
  backend/test/com/sims/qsc/inspection_result/mapper/InspectionResultPopupMapperTest.java
Labels: 🎨Html&css, 🔨Refactor

#145 [Test]: 점검결과 응답속도 최적화 전 테스트 #144
  backend/src/main/java/com/sims/qsc/inspection_result/service/inspectionResultPopup/InspectionResultPopupServiceImpl.java
  backend/src/main/resources/mapper/qsc/inspection_result/inspectionResultPopupMapper.xml
  backend/src/main/webapp/WEB-INF/views/master/store_manage/store_list.jsp
  backend/src/main/webapp/resources/css/master/product_manage/product_list.css
  backend/src/main/webapp/resources/css/qsc/inspection_result/popup_inspection_result.css
  backend/src/main/webapp/resources/css/qsc/inspection_result/result_list.css
  backend/src/main/webapp/resources/js/qsc/inspection_result/popup_inspection_result.js
  backend/src/main/webapp/resources/js/qsc/inspection_result/result.js
Labels: ✅Test

#146 [Test]: 점검 결과 중간 최적화 Test #144
  backend/src/main/resources/mapper/qsc/inspection_result/inspectionResultPopupMapper.xml
Labels: ✅Test

#147 [Test]: 점검결과 최적화 전 TEST #144
  backend/src/main/resources/mapper/qsc/inspection_result/inspectionResultPopupMapper.xml
Labels: ✅Test

#148 [Feat]: 가맹점 점검 로직 구현 #115
  backend/src/main/java/com/sims/qsc/inspection_schedule/service/InspectionScheduleServiceImpl.java
  backend/src/main/java/com/sims/qsc/store_inspection/vo/StoreAllLocationResponse.java
  backend/src/main/resources/mapper/qsc/inspection_schedule/InspectionScheduleMapper.xml
  backend/src/main/resources/mapper/qsc/store_inspection/storeInspectionMapper.xml
  backend/src/main/webapp/WEB-INF/views/qsc/inspection-schedule/schedule-list.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/inspection_result/popup_inspection_result.jsp
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/store-inspection.jsp
  backend/src/main/webapp/resources/css/qsc/store_inspection/store_inspection.css
  backend/src/main/webapp/resources/js/qsc/inspection_result/popup_inspection_result.js
  backend/src/main/webapp/resources/js/qsc/inspection_schedule/schedule_list.js
  backend/src/main/webapp/resources/js/qsc/store_inspection/maps.js
Labels: ✨Feature

#149 [Test]: 점검결과 TEST 최적화 #144
  backend/src/main/java/com/sims/qsc/inspection_result/service/inspectionResultPopup/InspectionResultPopupServiceImpl.java
  backend/src/main/resources/mapper/qsc/inspection_result/inspectionResultPopupMapper.xml
  backend/src/main/webapp/WEB-INF/views/qsc/inspection_result/popup_inspection_result.jsp
  backend/src/main/webapp/resources/js/qsc/inspection_result/popup_inspection_result.js
Labels: ✅Test

#150 [Fix]:가맹점 점검페이지 점검 JS 수정 #72
  backend/src/main/webapp/resources/css/qsc/store_inspection/store_inspection.css
  backend/src/main/webapp/resources/js/qsc/store_inspection/popup_middleCheck.js
Labels: 🐞BugFix

#151 [Fix]: 가맹점 점검페이지 점검유형 필터링 수정 #72
  backend/src/main/webapp/resources/js/qsc/store_inspection/store_inspection.js
Labels: 🐞BugFix

#153 [Feat]: 점검 결과 보고서 다운로드 기능 구현 #152
  backend/src/main/webapp/WEB-INF/views/qsc/inspection_result/popup_inspection_result.jsp
  backend/src/main/webapp/resources/css/qsc/inspection_result/popup_inspection_result.css
  backend/src/main/webapp/resources/js/qsc/inspection_result/popup_inspection_result.js
Labels: ✨Feature

#154 [Feat]: 점검 결과 보고서 기능 구현 #152
  backend/src/main/webapp/resources/js/qsc/inspection_result/popup_inspection_result.js
Labels: ✨Feature

#155 [Feat]: 가맹점 점검삽입,수정 스케줄러 구현 #115
  backend/src/main/java/com/sims/config/Exception/ErrorCode.java
  backend/src/main/java/com/sims/config/common/aop/RoleCheckAspect.java
  backend/src/main/java/com/sims/config/common/aop/SOnlyCheck.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/controller/InspectionScheduleRestController.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/mapper/InspectionScheduleMapper.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/service/InspectionScheduleService.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/service/InspectionScheduleServiceImpl.java
  backend/src/main/resources/mapper/qsc/inspection_schedule/InspectionScheduleMapper.xml
  backend/src/main/webapp/resources/js/qsc/inspection_schedule/schedule_list.js
Labels: ✨Feature

#156 [Fix]: 가맹점 점검 버튼 수정 #72
  backend/src/main/webapp/resources/js/qsc/store_inspection/store_inspection.js
Labels: 🐞BugFix, 🎨Html&css

#158 [UI]: 로그인 이미지 CSS 수정 #157
  backend/src/main/webapp/resources/css/home/login/login.css
Labels: 🎨Html&css

#159 [Fix]: 로그인 태블릿에서 이미지 오류 수정
  backend/src/main/webapp/resources/css/home/login/login.css
Labels: 🐞BugFix

#160 [Fix]: 점검결과 팝업 CSS 오류 수정
  backend/src/main/webapp/resources/js/qsc/inspection_result/popup_inspection_result.js
Labels: 🐞BugFix

#161 [Feat]: 가맹점 타임존 테스트 #115
  backend/src/main/java/com/sims/config/common/aop/RoleCheckAspect.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/controller/InspectionScheduleRestController.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/mapper/InspectionScheduleMapper.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/service/InspectionScheduleService.java
  backend/src/main/java/com/sims/qsc/inspection_schedule/service/InspectionScheduleServiceImpl.java
  backend/src/main/resources/mapper/qsc/inspection_schedule/InspectionScheduleMapper.xml
  backend/src/main/webapp/WEB-INF/views/qsc/inspection-schedule/schedule-list.jsp
  backend/src/main/webapp/resources/js/qsc/inspection_schedule/schedule_list.js
Labels: ✨Feature

#162 [Fix]: DB시간대 변경 테스트
  backend/src/main/resources/application.yml
Labels: 🐞BugFix

#163 [Fix]: DB Time Zone 잡기
  backend/src/main/resources/mapper/qsc/inspection_schedule/InspectionScheduleMapper.xml
Labels: 🐞BugFix

#164 [Feat]: 지도 js, css 수정 #90
  backend/src/main/webapp/WEB-INF/views/qsc/store_inspection/store-inspection.jsp
  backend/src/main/webapp/resources/css/qsc/store_inspection/store_inspection.css
  backend/src/main/webapp/resources/js/qsc/store_inspection/store_inspection.js
Labels: ✨Feature, 🎨Html&css

#165 [Fix] 통합 테스트 수정 #134
  backend/src/main/java/com/sims/config/Exception/ErrorCode.java
  backend/src/main/java/com/sims/config/common/ClientInfo.java
  backend/src/main/java/com/sims/config/s3/AwsFileService.java
  backend/src/main/java/com/sims/log/aop/TransactionErrorAspect.java
  backend/src/main/java/com/sims/log/aop/TransactionLogAspect.java
  backend/src/main/java/com/sims/master/checklist_manage/controller/ChecklistController.java
  backend/src/main/java/com/sims/master/checklist_manage/mapper/ChecklistMapper.java
  backend/src/main/java/com/sims/master/checklist_manage/service/ChecklistService.java
  backend/src/main/java/com/sims/master/checklist_manage/service/ChecklistServiceImpl.java
  backend/src/main/java/com/sims/master/checklist_manage/vo/Category.java
  backend/src/main/java/com/sims/master/checklist_manage/vo/ChecklistResponse.java
  backend/src/main/java/com/sims/master/checklist_manage/vo/Choice.java
  backend/src/main/java/com/sims/master/checklist_manage/vo/EvaluationItem.java
  backend/src/main/java/com/sims/master/inspection_list_manage/service/InspectionListManageServiceImpl.java
  backend/src/main/resources/mapper/master/checklist_manage/checklistMapper.xml
  backend/src/main/resources/mapper/master/checklist_manage/inspectionListManageMapper.xml
  backend/src/main/webapp/WEB-INF/views/home/dashboard/dashboard.jsp
  backend/src/main/webapp/WEB-INF/views/master/checklist/inspection_list_manage/inspection_list_manage.jsp
  backend/src/main/webapp/WEB-INF/views/master/checklist/list/checklist_list.jsp
  backend/src/main/webapp/resources/css/master/checklist/inspection_list_manage/inspection_list_manage.css
  backend/src/main/webapp/resources/css/master/checklist/list/checklist_list.css
  backend/src/main/webapp/resources/css/qsc/store_inspection/alert_error.css
  backend/src/main/webapp/resources/js/home/dashboard/dashboard.js
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/category.js
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/choice-list.js
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/evaluation.js
  backend/src/main/webapp/resources/js/master/checklist/inspection_list_manage/sub_category.js
  backend/src/main/webapp/resources/js/master/checklist/list/checklist.js
  backend/src/main/webapp/resources/js/master/checklist/list/checklist_filter.js
  backend/src/main/webapp/resources/js/master/checklist/list/checklist_modal.js
  backend/src/main/webapp/resources/js/master/checklist/list/checklist_second_modal.js
Labels: 🐞BugFix

#166 [Feat]: 가맹점 로딩애니메이션 추가 #115
  backend/src/main/resources/mapper/qsc/store_inspection/storeInspectionMapper.xml
  backend/src/main/webapp/resources/css/qsc/inspection_schedule/schedule_list.css
  backend/src/main/webapp/resources/js/qsc/inspection_schedule/schedule_list.js
Labels: 🎨Html&css

#167 [Fix]: Css 수정 #136
  backend/src/main/webapp/resources/css/master/checklist/list/checklist_list.css
  backend/src/main/webapp/resources/js/master/checklist/list/checklist.js
Labels: 🐞BugFix

#169 [Fix]: 점검결과 오류 수정
  backend/src/main/webapp/WEB-INF/views/master/store_manage/store_list.jsp
  backend/src/main/webapp/resources/js/master/store_manage/maps.js
  backend/src/main/webapp/resources/js/master/store_manage/store_list.js
  backend/src/main/webapp/resources/js/master/store_manage/store_modal.js
Labels: 🐞BugFix

#170 merge develop to main
  backend/src/main/webapp/WEB-INF/views/master/store_manage/store_list.jsp
  backend/src/main/webapp/resources/js/master/store_manage/maps.js
  backend/src/main/webapp/resources/js/master/store_manage/store_list.js
  backend/src/main/webapp/resources/js/master/store_manage/store_modal.js
Labels: 🌏Deploy
